export enum Category {
  Action = 'Action',
  RPG = 'RPG',
  ARPG = 'ARPG',
  SandBox = 'SandBox',
  RTS = 'RTS',
  FPS = 'FPS',
  TPS = 'TPS',
  MOBA = "MOBA",
  Simulation = "Simulation",
  Sport = "Sport",
  Racing = "Ricing",
  Platformer = "Platformer",
  Adventure = "Adventure",
  Survival = "Survival",
  Horror = "Horror",
  MultiPlayer = "MultiPlayer",
  COOP = "COOP",
  SinglePlayer = "SinglePlayer"
}
